services:
  mdbook-local:
    image: mdbook-local
    container_name: mdbook-local
    build:
      context: mdbook
      dockerfile: Dockerfile
  playground-local:
    image: playground-local
    container_name: playground-local
    build:
      context: playground
      dockerfile: Dockerfile
  robotframework-local:
    image: robotframework-local
    container_name: robotframework-local
    build:
      context: robotframework
      dockerfile: Dockerfile
