services:
  mdbook:
    build: mdbook
    image: mdbook:0.1.0
  playground:
    build: playground
    image: playground:0.1.0
  robotframework:
    build: robotframework
    image: robotframework:0.1.0
