format = """
$os\
[{](bold white)\
$username\
[@](bold white)\
$hostname\
[}](bold white)\
$directory\
$git_branch\
$git_status\
$package\
$python\
$rust\
$golang\
$nodejs\
$fill\
$cmd_duration\
$battery\
$time
[  └──](bold white)$character
"""

[os]
disabled = false
style = "bold white"
format = '[\[$symbol\]]($style)'

[os.symbols]
Arch = "Arc"
Debian = "Deb"
Fedora = "Fed"
Linux = "Lin"
Raspbian = "RPi"
Ubuntu = "Ubu"
Unknown = "Unk"
Windows = "Win"

[username]
show_always = true
style_root = "bold red"
style_user = "bold yellow"
format = '[$user]($style)'

[hostname]
ssh_only = false
style = 'bold green'
format = '[$hostname]($style)'

[directory]
style = "bold blue"
read_only = "ro"
read_only_style = "red"
format = '[\[$path\]]($style)'

[git_branch]
style = "bold white"
format = '[\[$branch\]]($style)'

[git_status]
disabled = false
style = "bold white"
format = '[\[$all_status\]]($style)'

[git_commit]
disabled = true

[git_state]
disabled = true

[package]
symbol = "pkg"
style = "bold purple"
format = '[\[$symbol $version\]]($style)'

[python]
symbol = "py"
style = "bold green"
format = '[\[$symbol $version\]]($style)'

[rust]
symbol = "rs"
style = "bold red"
format = '[\[$symbol $version\]]($style)'

[golang]
symbol = "go"
style = "bold cyan"
format = '[\[$symbol $version\]]($style)'

[nodejs]
symbol = "nodejs"
style = "bold yellow"
format = '[\[$symbol $version\]]($style)'

[fill]
symbol = "─"
style = "bold white"

[cmd_duration]
format = '[\[$duration\]](bold yellow)'
disabled = false

[battery]
disabled = false
format = '[\[$percentage\]]($style)'

[[battery.display]]
threshold = 100
style = "bold green"

[[battery.display]]
threshold = 50
style = "bold white"

[[battery.display]]
threshold = 15
style = "bold red"

[time]
disabled = false
style = "bold blue"
format = '[\[$time\]]($style)'

[character]
success_symbol = '[>](bold green)'
error_symbol = "[X](bold red)"
