name: DockerHub mdbook DEV
on:
  push:
    paths:
      - .github/workflows/mdbook_dev.yaml
      - mdbook/*
jobs:
  mdbook-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ./mdbook/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: thenerdlygentleman/mdbook:dev
