name: DockerHub playground PROD

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Enter Tag name'
        default: 'latest'
        required: true
        type: string

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ./playground/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: thenerdlygentleman/playground:${{ github.event.inputs.tag }}
