name: DockerHub playground DEV

on:
  push:
    paths:
      - .github/workflows/playground_dev.yaml
      - playground/*

env:
  TAG: thenerdlygentleman/playground:dev

jobs:
  test-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Test the image
        uses: docker/build-push-action@v6
        with:
          context: ./playground
          file: ./playground/Dockerfile
          target: test
          platforms: linux/amd64,linux/arm64
          push: false

      - name: Push dev tag
        uses: docker/build-push-action@v6
        with:
          context: ./playground
          file: ./playground/Dockerfile
          target: playground
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.TAG }}
